# Generated by Django 2.2.5 on 2020-02-26 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matchmaker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seqr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakersubmission',
            name='individual',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seqr.Individual'),
        ),
        migrations.AddField(
            model_name='matchmakerresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchmakerresult',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchmakerresult',
            name='originating_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchmaker.MatchmakerIncomingQuery'),
        ),
        migrations.AddField(
            model_name='matchmakerresult',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='matchmaker.MatchmakerSubmission'),
        ),
        migrations.AddField(
            model_name='matchmakerincomingquery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchmakercontactnotes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
